# Generated by Django 6.1.1 on 2026-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales_csv", "Sales CSV"),
                            ("orders_csv", "Orders CSV"),
                            ("products_csv", "Products CSV"),
                            ("sales_pdf", "Sales PDF"),
                        ],
                        max_length=30,
                    ),
                ),
                ("generated_by", models.CharField(max_length=150)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
